# Install (docker-py) python package as is a docker module dependency.
- pip: name=docker-py version=1.1.0

# tasks for running docker marathon
- name: run marathon container
  when: framework_marathon_enabled == "Y"
  docker:
    name: marathon
    image: "{{ marathon_image }}"
    state: started
    restart_policy: always
    net: host
    command: "--master {{marathon_master_peers}} --zk {{marathon_zk_peers}}"
    hostname: "{{ hostname }}"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

# tasks for stoping docker marathon
- name: stop marathon container
  when: framework_marathon_enabled == "N"
  docker:
    name: marathon
    image: "{{ marathon_image }}"
    state: stopped
    restart_policy: no
    net: host
    hostname: "{{ hostname }}"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"