---
- hosts: all
  roles:
    - dnsmasq
    - consul

- hosts: mesos_masters
  vars_prompt:
    - name: marathon_enabled
      prompt: "Do you want to deploy the marathon framework?(Y/N)"
      private: no
      default: "Y"
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
    - zookeeper
    - marathon
  vars:
    consul_is_server: true

- hosts: mesos_slaves
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
    - docker
    - weave
    - registrator

- hosts: load_balancers
  roles:
    - docker
    - weave
    - registrator
    - haproxy
