---
# defaults file for marathon
marathon_port: 8080
hostname: "{{ ansible_all_ipv4_addresses }}"
consul_dir: /etc/consul.d
marathon_server_zk_group: marathon_servers
marathon_local_address: "{{ansible_eth0.ipv4.address}}"
marathon_image: "mesosphere/marathon:v0.8.0"
marathon_peers_nodes: "
  {%- set marathon_peers = [] -%}
  {%- for host in groups[marathon_server_zk_group] -%}
    {%- if host not in marathon_peers -%}
      {%- set current_host = hostvars[host]['ansible_eth0']['ipv4']['address'] + ':' + zookeeper_client_port -%}
      {% do marathon_peers.append(current_host) %}
    {%- endif -%}
  {%- endfor -%}
  zk://{{ marathon_peers|join(',') }}
"
marathon_master_peers: "{{marathon_peers_nodes}}/mesos"
marathon_zk_peers: "{{marathon_peers_nodes}}/marathon"